### ISSUE TITLE
2.1.0 crash when open Refinery GUI

### ISSUE THREAD

**Issue by nalilord** [BCA-Team/Buildcraft-Additions#367]
The refinery was broken and no longer working (first blocks said it hat oil and power, the last blocks said nope nothing), so i broke one block and replaced it, after it reformed the structure opening the GUI was no longer possible!

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 4/6/15 12:40 PM
Description: Rendering screen

java.lang.ArithmeticException: / by zero
	at buildcraftAdditions.client.gui.GuiRefinery.drawBackgroundPostWidgets(GuiRefinery.java:57)
	at buildcraftAdditions.client.gui.GuiBase.func_146976_a(GuiBase.java:153)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at buildcraftAdditions.client.gui.GuiBase.func_73863_a(GuiBase.java:201)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraftAdditions.client.gui.GuiRefinery.drawBackgroundPostWidgets(GuiRefinery.java:57)
	at buildcraftAdditions.client.gui.GuiBase.func_146976_a(GuiBase.java:153)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at buildcraftAdditions.client.gui.GuiBase.func_73863_a(GuiBase.java:201)

-- Screen render details --
Details:
	Screen name: buildcraftAdditions.client.gui.GuiRefinery
	Mouse location: Scaled: (480, 254). Absolute: (960, 508)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2

**Comment by AEnterprise** [comment]
has already been fixed
https://github.com/BCA-Team/Buildcraft-Additions/commit/599b1b3468c292724766e631122a8858bbcee967
