### ISSUE TITLE
Eureka crash when crafting certain tools in the crafting table

### ISSUE THREAD

**Issue by AndrewCFairman** [BCA-Team/Buildcraft-Additions#385]
Crashes to desktop when attempting to craft an iron axe or an iron pick at the crafting table (only tools I've tested so far).  Was attempting to craft tools for use by BC robots.  When recipe Items are placed in the crafting table and then the crafted item is removed from the table, the crash takes place.  The crash log appears to indicate it's a problem with Eureka, but not sure (using Eureka 2.2).  Eureka is disabled in the config.  Mods I'm also using are NEI and Tinkers Construct (latest for 1.7.10).  Also using latest BC (6.4.11) and BCA (2.1.2).  Same crash occurred using the latest prior versions as well.  

Thanks!

Crash log:  (My first time posting a crash log so apologies if there's a better place to post and provide a link instead.  Let me know if so.)
----------------------------------------------------------------------------------------------------------------

java.lang.NoClassDefFoundError: eureka/api/EurekaAPI
	at buildcraftAdditions.core.EventListener$FML.onCrafted(EventListener.java:69)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_140_FML_onCrafted_ItemCraftedEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:570)
	at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:109)
	at tconstruct.tools.inventory.SlotCraftingStation.func_82870_a(SlotCraftingStation.java:30)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:238)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:503)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: eureka.api.EurekaAPI
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 38 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraftAdditions.core.EventListener$FML.onCrafted(EventListener.java:69)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_140_FML_onCrafted_ItemCraftedEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:570)
	at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:109)
	at tconstruct.tools.inventory.SlotCraftingStation.func_82870_a(SlotCraftingStation.java:30)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:238)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:503)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

**Comment by iTitus** [comment]
Next time you can use www.gist.github.com ;)

**Comment by iTitus** [comment]
Please use the newest version of Eureka. It no longer auto-updates.

**Comment by AndrewCFairman** [comment]
That solved it, thanks iTitus.  I wasn't aware that I'd need to download Eureka separately from BCA.  I never saw that posted on the site.

Thanks again for the fix as well as the link.  :)
