### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Xen1290** [BCA-Team/Buildcraft-Additions#439]
Hi, with BCA 2.2.0 I get that error in console:
Forge 1481

 [14:31:41] [Thread-15/INFO] [BuildCraft Additions]: Trying to get the special list file...
[14:31:41] [Client thread/WARN] [FML]: ****************************************
[14:31:41] [Client thread/WARN] [FML]: * The object buildcraftAdditions.items.ItemRobotDebugTool@5504240c has been registered twice for the same name bcadditions:robotDebugTool.
[14:31:41] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:376)
[14:31:41] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:845)
[14:31:41] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:808)
[14:31:41] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:149)
[14:31:41] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:137)
[14:31:41] [Client thread/WARN] [FML]: * at buildcraftAdditions.compat.buildcraft.CompatBuildCraft.addRobotDebugTool(CompatBuildCraft.java:49)...
[14:31:41] [Client thread/WARN] [FML]: ****************************************
[14:31:41] [Client thread/INFO] [CarpentersBlocks]: Designs found: Bed(6), Chisel(9), FlowerPot(18), Tile(13)
[14:31:42] [Thread-15/INFO] [BuildCraft Additions]: Successfully downloaded and read the special list file!

**Comment by AEnterprise** [comment]
hmm, probably when i moved that tool i copied instead of moved the registration of it
